#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "Standing up dotbot-brew..."
cd $BASEDIR && git submodule update --init dotbot-brew/
echo "Standing up Vundle..."
cd $BASEDIR && git submodule update --init vim/bundle/Vundle.vim

echo "Handing off to dotbot!"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir dotbot-brew -c "${CONFIG}" "${@}"
