#!/bin/bash
#Because typing sudo before every package command is annoying

#Shell rules require these to be functions
sudo_apt(){
  sudo apt-get "$@"
}

sudo_yum(){
  sudo yum "$@"
}

sudo_dnf(){
  sudo dnf "$@"
}

sudo_emerge(){
  sudo emerge "$@"
}

alias apt-get=sudo_apt
alias yum=sudo_yum
alias dnf=sudo_dnf
alias emerge=sudo_emerge
